# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='img_url',
            field=models.CharField(default='http://imgur.com/gallery/mh8J6', max_length=100),
        ),
    ]
