# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_spell_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='img_url',
            field=models.CharField(default='https://www.cleverfiles.com/howto/wp-content/uploads/2016/08/mini.jpg', max_length=100),
        ),
    ]
