# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20170109_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='img_url',
            field=models.CharField(max_length=255),
        ),
    ]
