# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20170109_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='img_url',
        ),
        migrations.AddField(
            model_name='spell',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='spell_images'),
        ),
    ]
